### PR TITLE
Add speaker to the paragraph object

### PR DESCRIPTION
**Pull request by DamienDeepgram**
Resolves
https://github.com/deepgram/deepgram-dotnet-sdk/issues/137

### CODE REVIEW

**Comment by jpvajda** [comment]
@DamienDeepgram  Thanks for this PR, how did you test this?  I noticed all the tests were skipped in CI. I'm not sure what to make of that. 

```
 Deepgram.Tests -> /home/runner/work/deepgram-dotnet-sdk/deepgram-dotnet-sdk/Deepgram.Tests/bin/Debug/net7.0/Deepgram.Tests.dll
Test run for /home/runner/work/deepgram-dotnet-sdk/deepgram-dotnet-sdk/Deepgram.Tests/bin/Debug/net7.0/Deepgram.Tests.dll (.NETCoreApp,Version=v7.0)
Microsoft (R) Test Execution Command Line Tool Version 17.7.1 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:    69, Skipped:     0, Total:    69, Duration: 3 s - Deepgram.Tests.dll (net7.0)
```

```
Deepgram.Tests -> /home/runner/work/deepgram-dotnet-sdk/deepgram-dotnet-sdk/Deepgram.Tests/bin/Debug/net7.0/Deepgram.Tests.dll
Test run for /home/runner/work/deepgram-dotnet-sdk/deepgram-dotnet-sdk/Deepgram.Tests/bin/Debug/net7.0/Deepgram.Tests.dll (.NETCoreApp,Version=v7.0)
Microsoft (R) Test Execution Command Line Tool Version 17.7.0-preview-23364-03+bc17bb9693cfc4778ded51aa0ab7f1065433f989 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:    69, Skipped:     0, Total:    69, Duration: 2 s - Deepgram.Tests.dll (net7.0)
```

**Review by jjmaldonis — APPROVED** [review]

**Comment by jpvajda** [comment]
Let's not merge until we confirm this has been tested.

**Comment by DamienDeepgram** [comment]
I tested this change to confirm it works but I have no idea why all the tests were skipped.

Do the tests usually run? The last PR also had all tests skipped it seems
https://github.com/deepgram/deepgram-dotnet-sdk/actions/runs/6150786086/job/16689477849?pr=132

**Comment by DamienDeepgram** [comment]
Oh I misread the test results all 69 passed

image

**Comment by jpvajda** [comment]
@DamienDeepgram  oh yes that comma.. 🤣  I mis-read those test results as well. This LGTM now.

**Pull request merged**
